"""
RAG service for the AI Teaching Assistant.

Flow:

Question
    ↓
Question normalization
    ↓
Question intent detection
    ↓
Query embedding
    ↓
Vector retrieval
    ↓
Keyword / phrase matching
    ↓
Title matching
    ↓
Question-type scoring
    ↓
Reranking
    ↓
Evidence validation
    ↓
Relevant evidence
    ↓
Answer
    ↓
Transcript timestamps

Important:

- Answers come only from uploaded course material.
- Timestamps are NEVER generated by the LLM.
- Only READY videos are searched.
- Deleted videos are excluded.
- Simple definition questions are answered directly from transcript evidence.
- List/classification questions require stronger evidence.
- Location questions are answered directly from retrieved evidence.
- Qwen is used only when synthesis is actually required.
- Weak or unrelated retrieved evidence is rejected before answer generation.
"""

import re
import threading
import time

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

from config import Config
from models import Video, STATUS_READY
from services import ollama_service


# =========================================================
# CONSTANTS
# =========================================================

EMBEDDING_COLUMNS = [
    "video_id",
    "number",
    "title",
    "start",
    "end",
    "text",
    "chunk_id",
    "embedding",
]

NOT_FOUND_MESSAGE = (
    "I couldn't find this information in the uploaded course material."
)

# ---------------------------------------------------------
# Evidence validation thresholds
# ---------------------------------------------------------

EVIDENCE_MIN_SCORE = 0.48
EVIDENCE_MIN_VECTOR = 0.42
EVIDENCE_MIN_TEXT_SUPPORT = 0.28

# Definition questions need stronger evidence because
# returning an incorrect definition is worse than returning
# "not found".
DEFINITION_MIN_SENTENCE_SCORE = 0.35
DEFINITION_MIN_TOPIC_SCORE = 0.40

# List/classification questions also need strong evidence.
LIST_MIN_TOPIC_SCORE = 0.70
LIST_MIN_VECTOR_SCORE = 0.40


# =========================================================
# GLOBAL CACHE
# =========================================================

EMBEDDINGS_DF = None
EMBEDDING_MATRIX = None

INDEX_LOCK = threading.RLock()


# =========================================================
# STOP WORDS
# =========================================================

STOP_WORDS = {
    "a",
    "an",
    "and",
    "are",
    "be",
    "been",
    "being",
    "but",
    "by",
    "can",
    "could",
    "did",
    "do",
    "does",
    "for",
    "from",
    "had",
    "has",
    "have",
    "how",
    "i",
    "in",
    "is",
    "it",
    "its",
    "me",
    "of",
    "on",
    "or",
    "please",
    "should",
    "tell",
    "that",
    "the",
    "their",
    "them",
    "this",
    "to",
    "us",
    "was",
    "we",
    "were",
    "what",
    "when",
    "where",
    "which",
    "who",
    "why",
    "will",
    "with",
    "would",
    "you",
    "your",
    "about",
    "explain",
    "give",
    "show",
    "know",
    "teach",
    "teaches",
    "taught",
    "learn",
    "learned",
    "lecture",
    "lectures",
    "video",
}


# =========================================================
# TOPIC EXPANSIONS
# =========================================================

TOPIC_EXPANSIONS = {
    "ml": "machine learning",
    "ai": "artificial intelligence",
    "js": "javascript",
    "css": "cascading style sheets",
    "html5": "html",
    "db": "database",
    "sql": "structured query language",
    "nlp": "natural language processing",
    "cv": "computer vision",
}


# =========================================================
# INDEX LOADING
# =========================================================

def load_embeddings_df(force_reload=False):
    """
    Load embeddings.joblib into memory.

    The dataframe and embedding matrix are cached so the
    embeddings file is not loaded for every question.
    """

    global EMBEDDINGS_DF
    global EMBEDDING_MATRIX

    if EMBEDDINGS_DF is not None and not force_reload:
        return EMBEDDINGS_DF

    with INDEX_LOCK:
        if EMBEDDINGS_DF is not None and not force_reload:
            return EMBEDDINGS_DF

        path = Config.EMBEDDINGS_PATH

        try:
            data = joblib.load(path)

        except FileNotFoundError:
            print(
                f"[RAG] Embeddings file not found: {path}"
            )

            EMBEDDINGS_DF = pd.DataFrame(
                columns=EMBEDDING_COLUMNS
            )

            EMBEDDING_MATRIX = np.empty(
                (0, 0),
                dtype=np.float32,
            )

            return EMBEDDINGS_DF

        except Exception as exc:
            print(
                f"[RAG] Could not load embeddings: {exc}"
            )
            raise

        # -------------------------------------------------
        # Convert loaded object to DataFrame
        # -------------------------------------------------

        if isinstance(data, pd.DataFrame):
            df = data.copy()

        elif isinstance(data, dict):
            df = pd.DataFrame(data)

        elif isinstance(data, list):
            df = pd.DataFrame(data)

        else:
            raise ValueError(
                "Unsupported embeddings.joblib format."
            )

        # -------------------------------------------------
        # Validate columns
        # -------------------------------------------------

        missing = [
            column
            for column in EMBEDDING_COLUMNS
            if column not in df.columns
        ]

        if missing:
            raise ValueError(
                "embeddings.joblib is missing required "
                f"columns: {missing}"
            )

        # -------------------------------------------------
        # Normalize dataframe
        # -------------------------------------------------

        df["video_id"] = (
            df["video_id"]
            .fillna("")
            .astype(str)
        )

        df["title"] = (
            df["title"]
            .fillna("")
            .astype(str)
        )

        df["text"] = (
            df["text"]
            .fillna("")
            .astype(str)
        )

        df["chunk_id"] = (
            df["chunk_id"]
            .fillna("")
            .astype(str)
        )

        df["number"] = (
            df["number"]
            .fillna("")
            .astype(str)
        )

        df["start"] = pd.to_numeric(
            df["start"],
            errors="coerce",
        ).fillna(0.0)

        df["end"] = pd.to_numeric(
            df["end"],
            errors="coerce",
        ).fillna(0.0)

        # -------------------------------------------------
        # Build embedding matrix
        # -------------------------------------------------

        vectors = []
        valid_rows = []

        for index, value in df["embedding"].items():
            try:
                vector = np.asarray(
                    value,
                    dtype=np.float32,
                )

                if vector.ndim != 1:
                    continue

                if vector.size == 0:
                    continue

                if not np.all(np.isfinite(vector)):
                    continue

                vectors.append(vector)
                valid_rows.append(index)

            except Exception:
                continue

        if len(valid_rows) != len(df):
            df = (
                df.loc[valid_rows]
                .reset_index(drop=True)
            )

        if vectors:
            dimensions = {
                vector.shape[0]
                for vector in vectors
            }

            if len(dimensions) != 1:
                raise ValueError(
                    "Embeddings have inconsistent dimensions."
                )

            EMBEDDING_MATRIX = np.vstack(
                vectors
            ).astype(np.float32)

        else:
            EMBEDDING_MATRIX = np.empty(
                (0, 0),
                dtype=np.float32,
            )

        EMBEDDINGS_DF = (
            df.reset_index(drop=True)
        )

        print(
            f"[RAG] Loaded {len(EMBEDDINGS_DF)} "
            "embedding chunks."
        )

        return EMBEDDINGS_DF


# =========================================================
# REBUILD EMBEDDING MATRIX
# =========================================================

def _rebuild_embedding_matrix():
    global EMBEDDING_MATRIX

    if (
        EMBEDDINGS_DF is None
        or EMBEDDINGS_DF.empty
    ):
        EMBEDDING_MATRIX = np.empty(
            (0, 0),
            dtype=np.float32,
        )
        return

    vectors = []

    for value in EMBEDDINGS_DF["embedding"]:
        vector = np.asarray(
            value,
            dtype=np.float32,
        )

        if vector.ndim != 1:
            raise ValueError(
                "Invalid embedding dimension."
            )

        if vector.size == 0:
            raise ValueError(
                "Empty embedding found."
            )

        vectors.append(vector)

    dimensions = {
        vector.shape[0]
        for vector in vectors
    }

    if len(dimensions) != 1:
        raise ValueError(
            "Embeddings have inconsistent dimensions."
        )

    EMBEDDING_MATRIX = np.vstack(
        vectors
    ).astype(np.float32)


# =========================================================
# SAVE INDEX
# =========================================================

def _save_embeddings():
    global EMBEDDINGS_DF

    if EMBEDDINGS_DF is None:
        return

    joblib.dump(
        EMBEDDINGS_DF,
        Config.EMBEDDINGS_PATH,
    )


# =========================================================
# ADD CHUNKS
# =========================================================

def add_chunks_to_index(chunks):
    """
    Embed and add transcript chunks to the RAG index.

    Existing chunks belonging to the same video are removed
    before the new chunks are inserted.
    """

    global EMBEDDINGS_DF

    if not chunks:
        return

    valid_chunks = []

    for chunk in chunks:
        text = str(
            chunk.get("text", "")
        ).strip()

        if not text:
            continue

        video_id = chunk.get("video_id")

        if video_id is None:
            continue

        try:
            start = float(
                chunk.get("start", 0)
            )
        except Exception:
            start = 0.0

        try:
            end = float(
                chunk.get("end", 0)
            )
        except Exception:
            end = start

        valid_chunks.append(
            {
                "video_id": str(video_id),
                "number": str(
                    chunk.get("number", "")
                ),
                "title": str(
                    chunk.get("title", "")
                ),
                "start": start,
                "end": end,
                "text": text,
                "chunk_id": str(
                    chunk.get(
                        "chunk_id",
                        f"{video_id}_{start}",
                    )
                ),
            }
        )

    if not valid_chunks:
        return

    texts = [
        chunk["text"]
        for chunk in valid_chunks
    ]

    print(
        f"[RAG] Creating embeddings for "
        f"{len(texts)} chunks..."
    )

    started = time.perf_counter()

    embeddings = ollama_service.create_embedding(
        texts
    )

    elapsed = (
        time.perf_counter()
        - started
    )

    if len(embeddings) != len(valid_chunks):
        raise ValueError(
            "Ollama returned a different number "
            "of embeddings than requested."
        )

    rows = []

    for chunk, embedding in zip(
        valid_chunks,
        embeddings,
    ):
        row = dict(chunk)
        row["embedding"] = embedding
        rows.append(row)

    new_df = pd.DataFrame(
        rows,
        columns=EMBEDDING_COLUMNS,
    )

    with INDEX_LOCK:
        if EMBEDDINGS_DF is None:
            load_embeddings_df()

        if EMBEDDINGS_DF is None:
            EMBEDDINGS_DF = pd.DataFrame(
                columns=EMBEDDING_COLUMNS
            )

        video_ids = set(
            new_df["video_id"]
            .astype(str)
        )

        # Remove old chunks from this video.
        if not EMBEDDINGS_DF.empty:
            EMBEDDINGS_DF = (
                EMBEDDINGS_DF[
                    ~EMBEDDINGS_DF[
                        "video_id"
                    ]
                    .astype(str)
                    .isin(video_ids)
                ]
                .reset_index(drop=True)
            )

        EMBEDDINGS_DF = pd.concat(
            [
                EMBEDDINGS_DF,
                new_df,
            ],
            ignore_index=True,
        )

        _rebuild_embedding_matrix()
        _save_embeddings()

    print(
        f"[RAG] Added {len(new_df)} chunks "
        f"in {elapsed:.2f}s."
    )

    # Return the number of chunks actually added so the
    # processing pipeline can report the correct count.
    return len(new_df)


# =========================================================
# REMOVE VIDEO
# =========================================================

def remove_video_from_index(video_id):
    """
    Remove all chunks belonging to a video.
    """

    global EMBEDDINGS_DF

    if video_id is None:
        return

    target_id = str(video_id)

    with INDEX_LOCK:
        if EMBEDDINGS_DF is None:
            load_embeddings_df()

        if (
            EMBEDDINGS_DF is None
            or EMBEDDINGS_DF.empty
        ):
            return

        before = len(
            EMBEDDINGS_DF
        )

        EMBEDDINGS_DF = (
            EMBEDDINGS_DF[
                EMBEDDINGS_DF[
                    "video_id"
                ]
                .astype(str)
                != target_id
            ]
            .reset_index(drop=True)
        )

        removed = (
            before
            - len(EMBEDDINGS_DF)
        )

        _rebuild_embedding_matrix()
        _save_embeddings()

    print(
        f"[RAG] Removed {removed} chunks "
        f"for video {target_id}."
    )


# =========================================================
# QUESTION NORMALIZATION
# =========================================================

def _normalize_question(question):
    """
    Normalize natural-language questions.
    """

    text = str(
        question or ""
    ).strip()

    text = re.sub(
        r"\s+",
        " ",
        text,
    )

    text = text.lower()

    # -----------------------------------------------------
    # Contractions
    # -----------------------------------------------------

    text = text.replace(
        "what's",
        "what is",
    )

    text = text.replace(
        "where's",
        "where is",
    )

    # -----------------------------------------------------
    # Remove trailing punctuation
    # -----------------------------------------------------

    text = re.sub(
        r"[?!]+$",
        "",
        text,
    ).strip()

    # -----------------------------------------------------
    # Topic expansion
    # -----------------------------------------------------

    words = text.split()

    expanded_words = []

    for word in words:
        cleaned = re.sub(
            r"[^\w-]",
            "",
            word,
        )

        if cleaned in TOPIC_EXPANSIONS:
            expanded_words.extend(
                TOPIC_EXPANSIONS[
                    cleaned
                ].split()
            )
        else:
            expanded_words.append(
                word
            )

    text = " ".join(
        expanded_words
    )

    # -----------------------------------------------------
    # "where X taught"
    # -----------------------------------------------------

    text = re.sub(
        r"^where\s+(.+?)\s+taught$",
        r"where is \1 taught",
        text,
        flags=re.IGNORECASE,
    )

    # -----------------------------------------------------
    # "where X covered"
    # -----------------------------------------------------

    text = re.sub(
        r"^where\s+(.+?)\s+covered$",
        r"where is \1 covered",
        text,
        flags=re.IGNORECASE,
    )

    # -----------------------------------------------------
    # "where X discussed"
    # -----------------------------------------------------

    text = re.sub(
        r"^where\s+(.+?)\s+discussed$",
        r"where is \1 discussed",
        text,
        flags=re.IGNORECASE,
    )

    # -----------------------------------------------------
    # "what video teaches X"
    # -----------------------------------------------------

    match = re.match(
        r"^what\s+video\s+"
        r"(?:teaches|teach|taught)\s+"
        r"(.+?)$",
        text,
        flags=re.IGNORECASE,
    )

    if match:
        topic = match.group(1).strip()

        return (
            f"which video teaches {topic}"
        )

    # -----------------------------------------------------
    # "what video taught us"
    # -----------------------------------------------------

    if re.fullmatch(
        r"what\s+video\s+"
        r"(?:taught|teaches|teach)\s+"
        r"(?:us|me)",
        text,
        flags=re.IGNORECASE,
    ):
        return (
            "what is taught in this video"
        )

    # -----------------------------------------------------
    # "what is this video about"
    # -----------------------------------------------------

    if re.fullmatch(
        r"what\s+(?:is|was)\s+"
        r"(?:this\s+)?video\s+about",
        text,
        flags=re.IGNORECASE,
    ):
        return (
            "what is this video about"
        )

    # -----------------------------------------------------
    # "which video"
    # -----------------------------------------------------

    if re.fullmatch(
        r"which\s+video",
        text,
        flags=re.IGNORECASE,
    ):
        return "which video"

    return text


# =========================================================
# TOKENIZATION
# =========================================================

def _raw_tokens(text):
    if not text:
        return []

    return re.findall(
        r"[a-zA-Z0-9]+(?:['-][a-zA-Z0-9]+)*",
        str(text).lower(),
    )


def _tokenize(text):
    tokens = _raw_tokens(text)

    return [
        token
        for token in tokens
        if token not in STOP_WORDS
        and len(token) > 1
    ]


# =========================================================
# KEYWORD SCORE
# =========================================================

def _keyword_score(
    question,
    text,
):
    question_tokens = set(
        _tokenize(question)
    )

    text_tokens = set(
        _tokenize(text)
    )

    if not question_tokens:
        return 0.0

    if not text_tokens:
        return 0.0

    overlap = (
        question_tokens
        & text_tokens
    )

    return (
        len(overlap)
        / len(question_tokens)
    )


# =========================================================
# EXACT KEYWORD SCORE
# =========================================================

def _exact_keyword_score(
    question,
    text,
):
    question = str(
        question or ""
    ).lower()

    text = str(
        text or ""
    ).lower()

    if not question or not text:
        return 0.0

    question_tokens = _tokenize(
        question
    )

    if not question_tokens:
        return 0.0

    score = 0.0

    meaningful_phrase = " ".join(
        question_tokens
    )

    if (
        len(question_tokens) >= 2
        and meaningful_phrase in text
    ):
        score += 0.75

    text_tokens = set(
        _raw_tokens(text)
    )

    matched = sum(
        1
        for token in question_tokens
        if token in text_tokens
    )

    token_ratio = (
        matched
        / len(question_tokens)
    )

    score += (
        0.25
        * token_ratio
    )

    return min(
        score,
        1.0,
    )


# =========================================================
# TITLE SCORE
# =========================================================

def _title_score(
    question,
    title,
):
    question_tokens = set(
        _tokenize(question)
    )

    title_tokens = set(
        _tokenize(title)
    )

    if not question_tokens:
        return 0.0

    if not title_tokens:
        return 0.0

    overlap = (
        question_tokens
        & title_tokens
    )

    score = (
        len(overlap)
        / len(question_tokens)
    )

    question_text = " ".join(
        _tokenize(question)
    )

    title_text = " ".join(
        _tokenize(title)
    )

    if (
        len(question_text.split()) >= 2
        and question_text in title_text
    ):
        score = max(
            score,
            1.0,
        )

    return min(
        score,
        1.0,
    )


# =========================================================
# EXACT PHRASE SCORE
# =========================================================

def _phrase_score(
    question,
    text,
):
    question_tokens = _tokenize(
        question
    )

    if len(question_tokens) < 2:
        return 0.0

    phrase = " ".join(
        question_tokens
    )

    normalized_text = re.sub(
        r"\s+",
        " ",
        str(text).lower(),
    )

    if phrase in normalized_text:
        return 1.0

    return 0.0


# =========================================================
# QUESTION TYPE
# =========================================================

def _detect_question_type(question):
    text = str(
        question or ""
    ).lower().strip()

    # -----------------------------------------------------
    # Location / lecture lookup
    # -----------------------------------------------------

    location_patterns = [
        r"^where\s+",
        r"^which\s+video",
        r"^what\s+video",
        r"^in\s+which\s+video",
        r"^where\s+is",
        r"^where\s+was",
        r"^where\s+are",
        r"^where\s+were",
    ]

    for pattern in location_patterns:
        if re.search(
            pattern,
            text,
        ):
            return "location"

    # -----------------------------------------------------
    # Definition
    # -----------------------------------------------------

    definition_patterns = [
        r"^what\s+is\s+",
        r"^what\s+are\s+",
        r"^who\s+is\s+",
        r"^what\s+does\s+.+\s+mean",
        r"^define\s+",
        r"^definition\s+of\s+",
        r"^meaning\s+of\s+",
        r"^what\s+is\s+the\s+meaning\s+of\s+",
    ]

    for pattern in definition_patterns:
        if re.search(
            pattern,
            text,
        ):
            return "definition"

    # -----------------------------------------------------
    # Comparison
    # -----------------------------------------------------

    if (
        "difference between" in text
        or "differences between" in text
        or "compare" in text
        or "comparison between" in text
        or "versus" in text
        or " vs " in f" {text} "
    ):
        return "comparison"

    # -----------------------------------------------------
    # How-to
    # -----------------------------------------------------

    if (
        text.startswith("how ")
        or "how to " in text
        or "steps to " in text
        or "procedure for " in text
    ):
        return "how_to"

    # -----------------------------------------------------
    # Example
    # -----------------------------------------------------

    if (
        "example" in text
        or "examples" in text
        or "give an example" in text
    ):
        return "example"

    # -----------------------------------------------------
    # Overview
    # -----------------------------------------------------

    if (
        "what is this video about" in text
        or "what does this video cover" in text
        or "summarize" in text
        or "summary" in text
        or "overview" in text
    ):
        return "overview"

    # -----------------------------------------------------
    # List / classification
    #
    # This is intentionally checked after definition.
    # For example:
    #
    # "What are the types of AI?"
    #
    # should be treated as a list question rather than
    # a generic "what are" definition question.
    # -----------------------------------------------------

    list_patterns = [
        r"^what\s+are\s+the\s+types\s+of\s+",
        r"^what\s+are\s+the\s+kinds\s+of\s+",
        r"^what\s+are\s+the\s+categories\s+of\s+",
        r"^what\s+are\s+the\s+subsets\s+of\s+",
        r"^types\s+of\s+",
        r"^kinds\s+of\s+",
        r"^categories\s+of\s+",
        r"^subsets\s+of\s+",
    ]

    for pattern in list_patterns:
        if re.search(
            pattern,
            text,
        ):
            return "list"

    return "general"


# =========================================================
# QUESTION TOPIC EXTRACTION
# =========================================================

def _extract_question_topic(question):
    text = _normalize_question(
        question
    )

    patterns = [
        r"^what\s+is\s+(.+?)$",
        r"^what\s+are\s+(.+?)$",
        r"^define\s+(.+?)$",
        r"^definition\s+of\s+(.+?)$",
        r"^meaning\s+of\s+(.+?)$",
        r"^what\s+does\s+(.+?)\s+mean$",
        r"^who\s+is\s+(.+?)$",
    ]

    for pattern in patterns:
        match = re.match(
            pattern,
            text,
            flags=re.IGNORECASE,
        )

        if match:
            topic = match.group(1).strip()

            topic = re.sub(
                r"[?.!]+$",
                "",
                topic,
            ).strip()

            return topic

    return ""


# =========================================================
# LIST TOPIC EXTRACTION
# =========================================================

def _extract_list_topic(question):
    """
    Extract the topic from list/classification questions.

    Examples:

        What are the types of artificial intelligence?
        -> artificial intelligence

        Types of machine learning
        -> machine learning
    """

    text = _normalize_question(
        question
    )

    patterns = [
        r"^what\s+are\s+the\s+types\s+of\s+(.+?)$",
        r"^what\s+are\s+the\s+kinds\s+of\s+(.+?)$",
        r"^what\s+are\s+the\s+categories\s+of\s+(.+?)$",
        r"^what\s+are\s+the\s+subsets\s+of\s+(.+?)$",
        r"^types\s+of\s+(.+?)$",
        r"^kinds\s+of\s+(.+?)$",
        r"^categories\s+of\s+(.+?)$",
        r"^subsets\s+of\s+(.+?)$",
    ]

    for pattern in patterns:
        match = re.match(
            pattern,
            text,
            flags=re.IGNORECASE,
        )

        if match:
            return match.group(1).strip()

    return ""


# =========================================================
# QUESTION TYPE SCORE
# =========================================================

def _question_type_score(
    question,
    text,
    title,
):
    qtype = _detect_question_type(
        question
    )

    text_lower = str(
        text or ""
    ).lower()

    title_lower = str(
        title or ""
    ).lower()

    score = 0.0

    if qtype == "definition":
        definition_terms = [
            " is ",
            " are ",
            " means ",
            " refers to ",
            " defined as ",
            " known as ",
            " called ",
            " is a ",
            " is an ",
            " stands for ",
            " branch of ",
        ]

        if any(
            term in f" {text_lower} "
            for term in definition_terms
        ):
            score += 0.8

        if (
            "definition" in text_lower
            or "define" in text_lower
        ):
            score += 0.2

    elif qtype == "list":
        list_terms = [
            "there are",
            "types are",
            "types include",
            "classified into",
            "divided into",
            "categories include",
            "kinds include",
            "consists of",
            "classification",
        ]

        if any(
            term in text_lower
            for term in list_terms
        ):
            score = 1.0

        elif any(
            term in text_lower
            for term in [
                "first",
                "second",
                "third",
                "one type",
                "another type",
            ]
        ):
            score = 0.6

    elif qtype == "location":
        if title_lower:
            score += 0.5

        if text_lower:
            score += 0.5

    elif qtype == "how_to":
        how_terms = [
            "step",
            "first",
            "then",
            "next",
            "finally",
            "process",
            "procedure",
            "create",
            "install",
            "use",
        ]

        if any(
            term in text_lower
            for term in how_terms
        ):
            score = 1.0

    elif qtype == "comparison":
        comparison_terms = [
            "difference",
            "different",
            "whereas",
            "while",
            "compared",
            "versus",
            "both",
        ]

        if any(
            term in text_lower
            for term in comparison_terms
        ):
            score = 1.0

    elif qtype == "example":
        example_terms = [
            "example",
            "for example",
            "such as",
            "instance",
        ]

        if any(
            term in text_lower
            for term in example_terms
        ):
            score = 1.0

    elif qtype == "overview":
        if title_lower:
            score += 0.4

        if len(text_lower) > 100:
            score += 0.6

    return min(
        score,
        1.0,
    )


# =========================================================
# ACTIVE VIDEO IDS
# =========================================================

def _get_ready_video_ids():
    try:
        rows = (
            Video.query
            .filter(
                Video.status == STATUS_READY
            )
            .all()
        )

        return {
            str(video.id)
            for video in rows
        }

    except Exception as exc:
        print(
            f"[RAG] Could not read READY "
            f"videos from database: {exc}"
        )

        return set()


# =========================================================
# RETRIEVAL
# =========================================================

def _retrieve(
    question,
    video_id=None,
):
    started = time.perf_counter()

    df = load_embeddings_df()

    if (
        df is None
        or df.empty
    ):
        return []

    with INDEX_LOCK:
        matrix = (
            None
            if EMBEDDING_MATRIX is None
            else EMBEDDING_MATRIX.copy()
        )

        working_df = df.copy()

    if (
        matrix is None
        or matrix.size == 0
    ):
        return []

    ready_ids = _get_ready_video_ids()

    if not ready_ids:
        return []

    # -----------------------------------------------------
    # Only READY videos
    # -----------------------------------------------------

    mask = (
        working_df["video_id"]
        .astype(str)
        .isin(ready_ids)
    )

    # -----------------------------------------------------
    # Optional selected video
    # -----------------------------------------------------

    if video_id is not None:
        mask = (
            mask
            & (
                working_df["video_id"]
                .astype(str)
                == str(video_id)
            )
        )

    candidate_df = (
        working_df.loc[mask]
        .reset_index(drop=True)
    )

    if candidate_df.empty:
        return []

    candidate_indices = (
        working_df.index[mask].to_numpy()
    )

    candidate_matrix = matrix[
        candidate_indices
    ]

    # -----------------------------------------------------
    # Normalize query
    # -----------------------------------------------------

    normalized_question = _normalize_question(
        question
    )

    # -----------------------------------------------------
    # Query embedding
    # -----------------------------------------------------

    embedding_started = time.perf_counter()

    query_embedding = (
        ollama_service.create_embedding(
            normalized_question
        )
    )

    embedding_elapsed = (
        time.perf_counter()
        - embedding_started
    )

    if not query_embedding:
        return []

    query_vector = np.asarray(
        query_embedding[0],
        dtype=np.float32,
    ).reshape(1, -1)

    # -----------------------------------------------------
    # Vector similarity
    # -----------------------------------------------------

    similarity_started = time.perf_counter()

    similarities = cosine_similarity(
        query_vector,
        candidate_matrix,
    )[0]

    similarity_elapsed = (
        time.perf_counter()
        - similarity_started
    )

    # -----------------------------------------------------
    # Calculate scores
    # -----------------------------------------------------

    scores = []

    for index, row in candidate_df.iterrows():
        vector_score = float(
            similarities[index]
        )

        keyword_score = _keyword_score(
            normalized_question,
            row["text"],
        )

        exact_keyword_score = (
            _exact_keyword_score(
                normalized_question,
                row["text"],
            )
        )

        title_score = _title_score(
            normalized_question,
            row["title"],
        )

        phrase_score = _phrase_score(
            normalized_question,
            row["text"],
        )

        question_type_score = (
            _question_type_score(
                normalized_question,
                row["text"],
                row["title"],
            )
        )

        # -------------------------------------------------
        # Final reranking score
        # -------------------------------------------------

        final_score = (
            0.50 * vector_score
            + 0.20 * keyword_score
            + 0.18 * exact_keyword_score
            + 0.07 * title_score
            + 0.05 * question_type_score
        )

        # Strong phrase match should matter.
        if phrase_score > 0:
            final_score += 0.08

        final_score = min(
            final_score,
            1.0,
        )

        scores.append(
            {
                "row": row,
                "vector_score": vector_score,
                "keyword_score": keyword_score,
                "exact_keyword_score": exact_keyword_score,
                "title_score": title_score,
                "phrase_score": phrase_score,
                "question_type_score": question_type_score,
                "score": final_score,
            }
        )

    # -----------------------------------------------------
    # Sort
    # -----------------------------------------------------

    scores.sort(
        key=lambda item: item["score"],
        reverse=True,
    )

    # -----------------------------------------------------
    # Adaptive threshold
    # -----------------------------------------------------

    configured_threshold = float(
        getattr(
            Config,
            "SIMILARITY_THRESHOLD",
            0.55,
        )
    )

    qtype = _detect_question_type(
        normalized_question
    )

    selected = []

    for item in scores:
        score = item["score"]
        vector_score = item["vector_score"]
        keyword_score = item["keyword_score"]
        phrase_score = item["phrase_score"]

        accepted = False

        if score >= configured_threshold:
            accepted = True

        # Exact topic matches deserve a chance even when
        # vector similarity is slightly lower.
        if phrase_score >= 1.0:
            if vector_score >= 0.30:
                accepted = True

        # Definition questions can use strong lexical
        # evidence because definitions are often short.
        if qtype == "definition":
            if (
                vector_score >= 0.40
                and keyword_score >= 0.50
            ):
                accepted = True

        # List questions need reasonable semantic support.
        if qtype == "list":
            if (
                vector_score >= 0.40
                and keyword_score >= 0.50
            ):
                accepted = True

        if accepted:
            selected.append(item)

    # -----------------------------------------------------
    # Fallback
    #
    # Validation below makes the final decision.
    # -----------------------------------------------------

    if not selected and scores:
        best = scores[0]

        if (
            best["vector_score"] >= 0.40
            or best["keyword_score"] >= 0.50
            or best["phrase_score"] >= 1.0
        ):
            selected = [best]

    # -----------------------------------------------------
    # Return top candidates
    # -----------------------------------------------------

    max_candidates = max(
        int(
            getattr(
                Config,
                "TOP_K",
                3,
            )
        ) * 4,
        8,
    )

    selected = selected[
        :max_candidates
    ]

    print(
        f"[RAG] Retrieval: "
        f"{len(candidate_df)} candidates, "
        f"{len(selected)} selected, "
        f"embedding={embedding_elapsed:.3f}s, "
        f"similarity={similarity_elapsed:.3f}s, "
        f"total={time.perf_counter() - started:.3f}s"
    )

    # -----------------------------------------------------
    # Debug top results
    # -----------------------------------------------------

    for rank, item in enumerate(
        selected[:5],
        start=1,
    ):
        row = item["row"]

        print(
            "[RAG] "
            f"#{rank} "
            f"score={item['score']:.3f} "
            f"vector={item['vector_score']:.3f} "
            f"keyword={item['keyword_score']:.3f} "
            f"exact={item['exact_keyword_score']:.3f} "
            f"title={item['title_score']:.3f} "
            f"video={row['video_id']} "
            f"title={row['title']} "
            f"time={row['start']:.2f}-{row['end']:.2f}"
        )

    return selected


# =========================================================
# MERGE ADJACENT SOURCES
# =========================================================

def _merge_adjacent_sources(
    sources,
):
    if not sources:
        return []

    ordered = sorted(
        sources,
        key=lambda item: (
            str(
                item["row"]["video_id"]
            ),
            float(
                item["row"]["start"]
            ),
        ),
    )

    merged = []

    for item in ordered:
        row = item["row"]

        if not merged:
            merged.append(
                {
                    **item,
                    "row": row.copy(),
                }
            )
            continue

        previous = merged[-1]["row"]

        same_video = (
            str(
                previous["video_id"]
            )
            == str(
                row["video_id"]
            )
        )

        previous_end = float(
            previous["end"]
        )

        current_start = float(
            row["start"]
        )

        # Merge chunks that are very close together.
        if (
            same_video
            and current_start
            <= previous_end + 2.0
        ):
            previous["end"] = max(
                previous_end,
                float(row["end"]),
            )

            previous_text = str(
                previous["text"]
            ).strip()

            current_text = str(
                row["text"]
            ).strip()

            if current_text not in previous_text:
                previous["text"] = (
                    previous_text
                    + " "
                    + current_text
                ).strip()

            # Keep the best retrieval score.
            if (
                item["score"]
                > merged[-1]["score"]
            ):
                for key in [
                    "score",
                    "vector_score",
                    "keyword_score",
                    "exact_keyword_score",
                    "title_score",
                    "phrase_score",
                    "question_type_score",
                ]:
                    merged[-1][key] = item[key]

        else:
            merged.append(
                {
                    **item,
                    "row": row.copy(),
                }
            )

    # Sort by retrieval relevance again.
    merged.sort(
        key=lambda item: item["score"],
        reverse=True,
    )

    return merged


# =========================================================
# EVIDENCE TEXT SCORE
# =========================================================

def _text_evidence_score(
    question,
    text,
):
    """
    Measure how strongly the actual transcript text supports
    the question.

    Title relevance is intentionally excluded.
    """

    keyword_score = _keyword_score(
        question,
        text,
    )

    exact_score = _exact_keyword_score(
        question,
        text,
    )

    phrase_score = _phrase_score(
        question,
        text,
    )

    return min(
        1.0,
        (
            0.50 * keyword_score
            + 0.30 * exact_score
            + 0.20 * phrase_score
        ),
    )


# =========================================================
# LIST EVIDENCE HELPERS
# =========================================================

def _has_list_answer_language(text):
    """
    Return True only when the transcript contains language
    that actually presents or classifies items.

    This is deliberately different from simply checking
    whether the word "types" appears.

    Example rejected:

        "What are the different types?"

    Example accepted:

        "There are three types of AI..."

        "AI is classified into three categories..."

        "The types include supervised and unsupervised..."
    """

    text_lower = str(
        text or ""
    ).lower()

    positive_patterns = [
        r"\bthere\s+are\b",
        r"\bthere\s+is\b",
        r"\btypes?\s+(?:are|include|includes)\b",
        r"\bkinds?\s+(?:are|include|includes)\b",
        r"\bcategories?\s+(?:are|include|includes)\b",
        r"\bsubsets?\s+(?:are|include|includes)\b",
        r"\bclassified\s+into\b",
        r"\bclassifies\s+into\b",
        r"\bdivided\s+into\b",
        r"\bdivide\s+into\b",
        r"\bconsists\s+of\b",
        r"\bclassification\s+of\b",
        r"\bclassification\s+includes\b",
        r"\bcan\s+be\s+classified\b",
        r"\bcan\s+be\s+divided\b",
        r"\binclude[s]?\b",
    ]

    return any(
        re.search(
            pattern,
            text_lower,
        )
        for pattern in positive_patterns
    )


def _is_list_introduction(text):
    """
    Detect transcript sentences that introduce a list/topic
    without actually giving the list.

    These should NOT be used as answers.
    """

    text_lower = str(
        text or ""
    ).lower()

    introduction_patterns = [
        r"\bwe\s+are\s+going\s+to\s+cover\b",
        r"\bwe\s+will\s+cover\b",
        r"\bwe\s+are\s+going\s+to\s+discuss\b",
        r"\bwe\s+will\s+discuss\b",
        r"\bwe\s+are\s+going\s+to\s+learn\b",
        r"\bwe\s+will\s+learn\b",
        r"\btoday\s+we\s+are\s+going\s+to\b",
        r"\btoday\s+we\s+will\b",
        r"\bwhat\s+are\s+the\s+different\s+types\b",
        r"\bwhat\s+are\s+the\s+types\b",
        r"\bwhat\s+are\s+the\s+different\s+subsets\b",
        r"\bwhat\s+are\s+the\s+subsets\b",
        r"\bwe\s+are\s+going\s+to\s+look\s+at\b",
        r"\bwe\s+will\s+look\s+at\b",
        r"\bin\s+this\s+session\s+we\s+will\b",
        r"\bin\s+today's\s+session\s+we\s+will\b",
    ]

    return any(
        re.search(
            pattern,
            text_lower,
        )
        for pattern in introduction_patterns
    )


def _list_topic_score(
    topic,
    text,
):
    """
    Measure how strongly the requested list topic appears
    in the transcript.
    """

    if not topic:
        return 0.0

    keyword_score = _keyword_score(
        topic,
        text,
    )

    phrase_score = _phrase_score(
        topic,
        text,
    )

    return max(
        keyword_score,
        phrase_score,
    )


# =========================================================
# EVIDENCE VALIDATION
# =========================================================

def _validate_evidence(
    question,
    sources,
):
    """
    Validate retrieved evidence before allowing it to reach
    answer generation.

    Retrieval asks:

        "Could this chunk be relevant?"

    Validation asks:

        "Does this chunk provide enough actual transcript
         evidence to answer this question?"

    This is deterministic and does NOT call Qwen.
    """

    if not sources:
        return []

    normalized_question = _normalize_question(
        question
    )

    qtype = _detect_question_type(
        normalized_question
    )

    validated = []

    # -----------------------------------------------------
    # Definition topic
    # -----------------------------------------------------

    definition_topic = ""

    if qtype == "definition":
        definition_topic = _extract_question_topic(
            normalized_question
        )

    # -----------------------------------------------------
    # List topic
    # -----------------------------------------------------

    list_topic = ""

    if qtype == "list":
        list_topic = _extract_list_topic(
            normalized_question
        )

    # -----------------------------------------------------
    # Location topic
    # -----------------------------------------------------

    location_topic = ""

    if qtype == "location":
        location_topic = _extract_location_topic(
            normalized_question
        )

    # -----------------------------------------------------
    # Validate every candidate
    # -----------------------------------------------------

    for item in sources:
        row = item["row"]

        text = str(
            row.get("text", "")
        ).strip()

        title = str(
            row.get("title", "")
        ).strip()

        if not text:
            continue

        vector_score = float(
            item.get(
                "vector_score",
                0.0,
            )
        )

        keyword_score = _keyword_score(
            normalized_question,
            text,
        )

        exact_score = _exact_keyword_score(
            normalized_question,
            text,
        )

        phrase_score = _phrase_score(
            normalized_question,
            text,
        )

        text_support = _text_evidence_score(
            normalized_question,
            text,
        )

        # -------------------------------------------------
        # General evidence confidence
        # -------------------------------------------------

        evidence_score = (
            0.65 * vector_score
            + 0.35 * text_support
        )

        accepted = False

        # -------------------------------------------------
        # Definition validation
        # -------------------------------------------------

        if qtype == "definition":
            if definition_topic:
                topic_score = _keyword_score(
                    definition_topic,
                    text,
                )

                topic_phrase_score = _phrase_score(
                    definition_topic,
                    text,
                )

                best_definition_score = 0.0

                for sentence in _split_sentences(
                    text
                ):
                    sentence_score = (
                        _score_definition_sentence(
                            definition_topic,
                            sentence,
                        )
                    )

                    if (
                        sentence_score
                        > best_definition_score
                    ):
                        best_definition_score = (
                            sentence_score
                        )

                # A lecture does not always define a concept with
                # dictionary wording such as "X is a ...". It may
                # explain the concept across several sentences.
                # Strong semantic retrieval plus an explicit topic
                # occurrence is sufficient for Qwen to synthesize
                # a grounded definition from the transcript.
                strong_topic_evidence = (
                    (
                        topic_phrase_score >= 1.0
                        or topic_score >= 0.80
                    )
                    and vector_score >= 0.55
                )

                dictionary_definition = (
                    best_definition_score
                    >= DEFINITION_MIN_SENTENCE_SCORE
                    and (
                        topic_score
                        >= DEFINITION_MIN_TOPIC_SCORE
                        or topic_phrase_score >= 1.0
                    )
                    and vector_score >= 0.35
                )

                accepted = (
                    strong_topic_evidence
                    or dictionary_definition
                )

                evidence_score = max(
                    0.55 * vector_score
                    + 0.30 * topic_score
                    + 0.15 * best_definition_score,
                    0.65 * vector_score
                    + 0.35 * topic_score,
                )

        # -------------------------------------------------
        # List / classification validation
        # -------------------------------------------------

        elif qtype == "list":
            topic_score = _list_topic_score(
                list_topic,
                text,
            )

            has_list_language = (
                _has_list_answer_language(
                    text
                )
            )

            is_introduction = (
                _is_list_introduction(
                    text
                )
            )

            # -------------------------------------------------
            # IMPORTANT:
            #
            # "What are the different types?"
            # "We are going to cover the different types..."
            #
            # are NOT actual answers.
            # -------------------------------------------------

            accepted = (
                topic_score
                >= LIST_MIN_TOPIC_SCORE
                and has_list_language
                and not is_introduction
                and vector_score
                >= LIST_MIN_VECTOR_SCORE
            )

            evidence_score = (
                0.40 * vector_score
                + 0.40 * topic_score
                + 0.20 * (
                    1.0
                    if has_list_language
                    else 0.0
                )
            )

        # -------------------------------------------------
        # Location validation
        # -------------------------------------------------

        elif qtype == "location":
            if location_topic:
                topic_text_score = _keyword_score(
                    location_topic,
                    text,
                )

                topic_phrase_score = _phrase_score(
                    location_topic,
                    text,
                )

                accepted = (
                    topic_text_score >= 0.40
                    or topic_phrase_score >= 1.0
                )

                evidence_score = (
                    0.45 * vector_score
                    + 0.35 * topic_text_score
                    + 0.20 * topic_phrase_score
                )

            else:
                accepted = (
                    vector_score >= EVIDENCE_MIN_VECTOR
                    and text_support
                    >= EVIDENCE_MIN_TEXT_SUPPORT
                )

        # -------------------------------------------------
        # General / how-to / comparison / example / overview
        # -------------------------------------------------

        else:
            accepted = (
                evidence_score >= EVIDENCE_MIN_SCORE
                and (
                    vector_score >= EVIDENCE_MIN_VECTOR
                    or text_support
                    >= EVIDENCE_MIN_TEXT_SUPPORT
                )
            )

        if accepted:
            validated_item = dict(item)

            validated_item[
                "evidence_score"
            ] = min(
                1.0,
                float(evidence_score),
            )

            validated_item[
                "validated_keyword_score"
            ] = keyword_score

            validated_item[
                "validated_exact_score"
            ] = exact_score

            validated_item[
                "validated_phrase_score"
            ] = phrase_score

            validated.append(
                validated_item
            )

    # -----------------------------------------------------
    # Sort validated evidence
    # -----------------------------------------------------

    validated.sort(
        key=lambda item: (
            float(
                item.get(
                    "evidence_score",
                    0.0,
                )
            ),
            float(
                item.get(
                    "score",
                    0.0,
                )
            ),
        ),
        reverse=True,
    )

    # -----------------------------------------------------
    # Debug validation
    # -----------------------------------------------------

    print(
        f"[RAG] Evidence validation: "
        f"{len(sources)} candidates -> "
        f"{len(validated)} validated"
    )

    for rank, item in enumerate(
        validated[:5],
        start=1,
    ):
        row = item["row"]

        print(
            "[RAG] VALIDATED "
            f"#{rank} "
            f"evidence={item.get('evidence_score', 0):.3f} "
            f"retrieval={item.get('score', 0):.3f} "
            f"vector={item.get('vector_score', 0):.3f} "
            f"keyword={item.get('validated_keyword_score', 0):.3f} "
            f"video={row['video_id']} "
            f"title={row['title']} "
            f"time={row['start']:.2f}-{row['end']:.2f}"
        )

    if not validated:
        print(
            "[RAG] Evidence validation rejected all "
            "retrieved candidates."
        )

    return validated


# =========================================================
# TIMESTAMP
# =========================================================

def _format_timestamp(seconds):
    try:
        seconds = max(
            0,
            int(float(seconds)),
        )
    except Exception:
        seconds = 0

    hours = seconds // 3600

    minutes = (
        seconds % 3600
    ) // 60

    secs = seconds % 60

    if hours > 0:
        return (
            f"{hours}:{minutes:02d}:{secs:02d}"
        )

    return (
        f"{minutes}:{secs:02d}"
    )


# =========================================================
# SOURCE FORMAT
# =========================================================

def _source_dict(item):
    row = item["row"]

    return {
        "video_id": str(
            row["video_id"]
        ),

        "number": str(
            row.get("number", "")
        ),

        "title": str(
            row.get("title", "")
        ),

        "start": float(
            row.get("start", 0)
        ),

        "end": float(
            row.get("end", 0)
        ),

        "start_timestamp": _format_timestamp(
            row.get("start", 0)
        ),

        "end_timestamp": _format_timestamp(
            row.get("end", 0)
        ),

        "text": str(
            row.get("text", "")
        ).strip(),

        "score": round(
            float(
                item.get(
                    "score",
                    0,
                )
            ),
            4,
        ),

        "evidence_score": round(
            float(
                item.get(
                    "evidence_score",
                    item.get(
                        "score",
                        0,
                    ),
                )
            ),
            4,
        ),
    }


# =========================================================
# ANSWER CLEANING
# =========================================================

def _clean_answer(answer):
    if answer is None:
        return ""

    text = str(answer).strip()

    # -----------------------------------------------------
    # Remove Qwen thinking blocks
    # -----------------------------------------------------

    text = re.sub(
        r"<think>.*?</think>",
        "",
        text,
        flags=re.IGNORECASE | re.DOTALL,
    )

    text = re.sub(
        r"<thinking>.*?</thinking>",
        "",
        text,
        flags=re.IGNORECASE | re.DOTALL,
    )

    # -----------------------------------------------------
    # Remove answer wrappers
    # -----------------------------------------------------

    text = re.sub(
        r"</?answer>",
        "",
        text,
        flags=re.IGNORECASE,
    )

    # -----------------------------------------------------
    # Remove reference section
    # -----------------------------------------------------

    text = re.split(
        r"\n\s*(?:###\s*)?referenced in\s*:?\s*",
        text,
        flags=re.IGNORECASE,
    )[0]

    text = re.split(
        r"\n\s*(?:###\s*)?sources?\s*:?\s*",
        text,
        flags=re.IGNORECASE,
    )[0]

    # -----------------------------------------------------
    # Remove common reasoning/meta lines
    # -----------------------------------------------------

    reasoning_prefixes = (
        "okay, so",
        "ok, so",
        "hmm,",
        "the user",
        "the question",
        "we are given",
        "we need to",
        "we have to",
        "i need to",
        "i have to",
        "i should",
        "i must",
        "let me",
        "let's",
        "looking at",
        "according to the instructions",
        "according to the course material",
        "course material provided",
        "the evidence provided",
        "answer should",
        "i will answer",
        "we must",
        "we should",
        "first,",
        "first we",
        "therefore,",
        "thus,",
    )

    cleaned_lines = []

    for line in text.splitlines():
        stripped = line.strip()

        if not stripped:
            continue

        lower = stripped.lower()

        if any(
            lower.startswith(prefix)
            for prefix in reasoning_prefixes
        ):
            continue

        if (
            lower.startswith("###")
            or lower.startswith("reasoning:")
            or lower.startswith("analysis:")
        ):
            continue

        cleaned_lines.append(
            stripped
        )

    text = "\n".join(
        cleaned_lines
    ).strip()

    # -----------------------------------------------------
    # Remove unnecessary bullets
    # -----------------------------------------------------

    text = re.sub(
        r"^\s*[-*]\s+",
        "",
        text,
        flags=re.MULTILINE,
    )

    # -----------------------------------------------------
    # Remove excessive whitespace
    # -----------------------------------------------------

    text = re.sub(
        r"\n{3,}",
        "\n\n",
        text,
    )

    return text.strip()


# =========================================================
# DEFINITION SENTENCE SPLITTER
# =========================================================

def _split_sentences(text):
    text = str(
        text or ""
    ).strip()

    if not text:
        return []

    parts = re.split(
        r"(?<=[.!?])\s+",
        text,
    )

    result = []

    for part in parts:
        part = part.strip()

        if not part:
            continue

        result.append(part)

    return result


# =========================================================
# DEFINITION SENTENCE SCORING
# =========================================================

def _score_definition_sentence(
    topic,
    sentence,
):
    """
    Score a sentence as a possible definition.

    IMPORTANT:

    A topic mention alone is NOT considered a definition.

    Example:

        "Artificial intelligence every single day."

    is rejected.

    Example:

        "Machine learning is a branch of computer science..."

    is accepted.
    """

    topic_tokens = set(
        _tokenize(topic)
    )

    sentence_tokens = set(
        _tokenize(sentence)
    )

    if not topic_tokens:
        return 0.0

    if not sentence_tokens:
        return 0.0

    overlap = (
        topic_tokens
        & sentence_tokens
    )

    topic_overlap = (
        len(overlap)
        / len(topic_tokens)
    )

    lower = sentence.lower()

    # -----------------------------------------------------
    # A definition MUST contain an actual definition
    # pattern.
    # -----------------------------------------------------

    definition_patterns = [
        r"\bis\s+(?:a|an|the)\b",
        r"\bare\s+(?:a|an|the)\b",
        r"\bmeans\b",
        r"\brefers\s+to\b",
        r"\bis\s+defined\s+as\b",
        r"\bare\s+defined\s+as\b",
        r"\bknown\s+as\b",
        r"\bis\s+called\b",
        r"\bis\s+known\s+as\b",
        r"\bstands\s+for\b",
        r"\bbranch\s+of\b",
        r"\bis\s+the\s+process\b",
        r"\bis\s+a\s+process\b",
        r"\bis\s+an\s+approach\b",
        r"\bis\s+a\s+method\b",
        r"\bis\s+a\s+technique\b",
        # Lecture definitions are often phrased as actions rather
        # than dictionary-style "X is ..." sentences.
        r"\btrains\s+(?:a|an|the)\b",
        r"\buses\s+(?:a|an|the)\b",
        r"\buses\s+.+\bto\b",
        r"\binvolves\b",
        r"\bconsists\s+of\b",
        r"\bhelps\b",
    ]

    has_definition_pattern = any(
        re.search(
            pattern,
            lower,
        )
        for pattern in definition_patterns
    )

    # -----------------------------------------------------
    # Topic must actually be present.
    # -----------------------------------------------------

    if topic_overlap < 0.75:
        return 0.0

    # -----------------------------------------------------
    # Topic mention without definition = reject.
    # -----------------------------------------------------

    if not has_definition_pattern:
        return 0.0

    # -----------------------------------------------------
    # Strong definition evidence.
    # -----------------------------------------------------

    score = (
        0.55 * topic_overlap
        + 0.45
    )

    # -----------------------------------------------------
    # Prefer exact topic phrase.
    # -----------------------------------------------------

    topic_phrase = " ".join(
        _raw_tokens(topic)
    )

    normalized_sentence = " ".join(
        _raw_tokens(sentence)
    )

    if (
        topic_phrase
        and topic_phrase in normalized_sentence
    ):
        score += 0.10

    # -----------------------------------------------------
    # Penalize obvious conversational filler.
    # -----------------------------------------------------

    filler_patterns = [
        "hey guys",
        "hello guys",
        "today in this video",
        "in this video we are going to",
        "let us learn",
        "we are going to learn",
    ]

    for filler in filler_patterns:
        if filler in lower:
            score -= 0.08
            break

    return min(
        max(score, 0.0),
        1.0,
    )


# =========================================================
# EXTRACT CLEAN DEFINITION
# =========================================================

def _extract_definition_from_sentence(
    topic,
    sentence,
):
    sentence = str(
        sentence or ""
    ).strip()

    topic = str(
        topic or ""
    ).strip()

    if not sentence or not topic:
        return ""

    topic_words = _raw_tokens(
        topic
    )

    if not topic_words:
        return sentence

    topic_pattern = (
        r"\b"
        + r"\s+".join(
            re.escape(word)
            for word in topic_words
        )
        + r"\b"
    )

    match = re.search(
        topic_pattern,
        sentence,
        flags=re.IGNORECASE,
    )

    if match:
        extracted = sentence[
            match.start():
        ].strip()

    else:
        extracted = sentence

    # -----------------------------------------------------
    # Remove common introductory phrases
    # -----------------------------------------------------

    extracted = re.sub(
        r"^(?:today|in this video|in today's video)"
        r"(?:\s+we\s+(?:are|will)\s+going\s+to)?"
        r"\s+(?:learn|discuss|understand)\s+",
        "",
        extracted,
        flags=re.IGNORECASE,
    ).strip()

    # -----------------------------------------------------
    # Fix a few common Whisper artifacts
    # -----------------------------------------------------

    replacements = [
        (
            r"\bthe using of\b",
            "using",
        ),
        (
            r"\busing of data\b",
            "using data",
        ),
        (
            r"\buses of data\b",
            "uses data",
        ),
    ]

    for pattern, replacement in replacements:
        extracted = re.sub(
            pattern,
            replacement,
            extracted,
            flags=re.IGNORECASE,
        )

    # -----------------------------------------------------
    # Remove leading punctuation
    # -----------------------------------------------------

    extracted = re.sub(
        r"^[,;:\-*\s]+",
        "",
        extracted,
    ).strip()

    # -----------------------------------------------------
    # Make first character readable
    # -----------------------------------------------------

    if extracted:
        extracted = (
            extracted[0].upper()
            + extracted[1:]
        )

    return extracted


# =========================================================
# DEFINITION ANSWER
# =========================================================

def _definition_answer(
    question,
    sources,
):
    """
    Return the lecture's own definition wording.

    Definition questions should not be paraphrased by the LLM when
    the transcript already contains a direct explanation. We select
    the strongest definition sentence and, when the immediately
    following sentence clearly continues that definition, preserve it
    too. This keeps the answer faithful to the lecture wording.
    """

    topic = _extract_question_topic(
        question
    )

    if not topic:
        return None

    candidates = []

    for item in sources:
        row = item["row"]

        text = str(
            row.get("text", "")
        ).strip()

        if not text:
            continue

        sentences = _split_sentences(
            text
        )

        if not sentences:
            sentences = [text]

        for sentence_index, sentence in enumerate(
            sentences
        ):
            score = _score_definition_sentence(
                topic,
                sentence,
            )

            # A lecture may explain a concept without using an
            # explicit dictionary phrase. Reward a direct topic
            # sentence that contains an explanatory action.
            phrase_score = _phrase_score(
                topic,
                sentence,
            )

            keyword_score = _keyword_score(
                topic,
                sentence,
            )

            if phrase_score >= 1.0:
                score += 0.08

            if keyword_score >= 0.75:
                score += 0.04

            candidates.append(
                {
                    "sentence": sentence,
                    "sentence_index": sentence_index,
                    "sentences": sentences,
                    "score": min(score, 1.0),
                    "source": item,
                }
            )

    if not candidates:
        return None

    candidates.sort(
        key=lambda item: item["score"],
        reverse=True,
    )

    best = candidates[0]

    if (
        best["score"]
        < DEFINITION_MIN_SENTENCE_SCORE
    ):
        return None

    first_sentence = _extract_definition_from_sentence(
        topic,
        best["sentence"],
    )

    if not first_sentence:
        return None

    answer_sentences = [
        first_sentence
    ]

    # Preserve one immediately following sentence when it clearly
    # continues the definition, e.g. "It uses an agent...".
    next_index = (
        best["sentence_index"] + 1
    )

    sentences = best["sentences"]

    if next_index < len(sentences):
        next_sentence = str(
            sentences[next_index]
        ).strip()

        next_lower = next_sentence.lower()

        topic_overlap = _keyword_score(
            topic,
            next_sentence,
        )

        continuation = (
            topic_overlap >= 0.40
            or next_lower.startswith((
                "it ",
                "this ",
                "these ",
                "they ",
                "the agent ",
                "the environment ",
            ))
        )

        if continuation:
            answer_sentences.append(
                next_sentence
            )

    answer = " ".join(
        answer_sentences
    ).strip()

    meaningful_tokens = _tokenize(
        answer
    )

    if len(meaningful_tokens) < 3:
        return None

    print(
        "[RAG] Exact definition extracted: "
        f"{answer}"
    )

    return (
        answer,
        best["source"],
    )


# =========================================================
# LOCATION TOPIC EXTRACTION
# =========================================================

def _extract_location_topic(question):
    text = _normalize_question(
        question
    )

    patterns = [
        r"^where\s+is\s+(.+?)\s+taught$",
        r"^where\s+is\s+(.+?)\s+covered$",
        r"^where\s+is\s+(.+?)\s+discussed$",
        r"^which\s+video\s+teaches\s+(.+?)$",
        r"^in\s+which\s+video\s+is\s+(.+?)\s+taught$",
        r"^in\s+which\s+video\s+is\s+(.+?)\s+covered$",
    ]

    for pattern in patterns:
        match = re.match(
            pattern,
            text,
            flags=re.IGNORECASE,
        )

        if match:
            return match.group(1).strip()

    return ""


# =========================================================
# LOCATION ANSWER
# =========================================================

def _build_location_answer(
    question,
    sources,
):
    if not sources:
        return ""

    topic = _extract_location_topic(
        question
    )

    # -----------------------------------------------------
    # Simple "which video"
    # -----------------------------------------------------

    if not topic:
        if _normalize_question(
            question
        ) == "which video":

            row = sources[0]["row"]

            return (
                f'The relevant video is '
                f'"{row["title"]}".'
            )

        row = sources[0]["row"]

        return (
            f"This video covers the topic "
            f"discussed around "
            f"{_format_timestamp(row['start'])}."
        )

    # -----------------------------------------------------
    # Rank source videos by topic evidence
    # -----------------------------------------------------

    grouped = {}

    for item in sources:
        row = item["row"]

        video_id = str(
            row["video_id"]
        )

        text = str(
            row.get("text", "")
        )

        title = str(
            row.get("title", "")
        )

        text_score = _keyword_score(
            topic,
            text,
        )

        title_score = _title_score(
            topic,
            title,
        )

        phrase_score = _phrase_score(
            topic,
            text,
        )

        total = (
            0.55 * text_score
            + 0.25 * title_score
            + 0.20 * phrase_score
            + 0.20 * float(
                item.get(
                    "evidence_score",
                    item.get(
                        "score",
                        0,
                    ),
                )
            )
        )

        if video_id not in grouped:
            grouped[video_id] = {
                "video_id": video_id,
                "title": title,
                "number": str(
                    row.get("number", "")
                ),
                "score": total,
                "start": float(
                    row.get("start", 0)
                ),
                "end": float(
                    row.get("end", 0)
                ),
            }

        else:
            existing = grouped[
                video_id
            ]

            if total > existing["score"]:
                existing["score"] = total
                existing["start"] = float(
                    row.get("start", 0)
                )
                existing["end"] = float(
                    row.get("end", 0)
                )

    if not grouped:
        return ""

    ranked = sorted(
        grouped.values(),
        key=lambda item: item["score"],
        reverse=True,
    )

    best = ranked[0]

    # -----------------------------------------------------
    # Make sure topic exists in transcript evidence.
    # -----------------------------------------------------

    evidence_match = False

    for item in sources:
        row = item["row"]

        if str(
            row["video_id"]
        ) != best["video_id"]:
            continue

        text = str(
            row.get("text", "")
        )

        if (
            _keyword_score(
                topic,
                text,
            ) >= 0.40
            or _phrase_score(
                topic,
                text,
            ) >= 1.0
        ):
            evidence_match = True
            break

    if not evidence_match:
        return ""

    return (
        f"{best['title']} "
        f"({_format_timestamp(best['start'])}–"
        f"{_format_timestamp(best['end'])})"
    )


# =========================================================
# DEFINITION EVIDENCE SELECTION
# =========================================================

def _select_definition_sources(
    question,
    sources,
):
    """
    Select a very small, focused transcript excerpt for a
    definition question.

    Retrieval is intentionally broad, but definition generation
    should not receive several unrelated chunks. The best sentence
    is selected first and then given a small amount of local context.
    """

    topic = _extract_question_topic(
        question
    )

    if not topic or not sources:
        return sources[:1]

    candidates = []

    for source_index, item in enumerate(
        sources
    ):
        row = item["row"]
        text = str(
            row.get("text", "")
        ).strip()

        if not text:
            continue

        sentences = _split_sentences(
            text
        )

        if not sentences:
            sentences = [text]

        for sentence_index, sentence in enumerate(
            sentences
        ):
            sentence = str(
                sentence or ""
            ).strip()

            if not sentence:
                continue

            definition_score = _score_definition_sentence(
                topic,
                sentence,
            )

            phrase_score = _phrase_score(
                topic,
                sentence,
            )

            keyword_score = _keyword_score(
                topic,
                sentence,
            )

            retrieval_score = float(
                item.get(
                    "evidence_score",
                    item.get(
                        "score",
                        0,
                    ),
                )
            )

            total = (
                0.50 * definition_score
                + 0.25 * phrase_score
                + 0.15 * keyword_score
                + 0.10 * retrieval_score
            )

            candidates.append(
                {
                    "score": total,
                    "source_index": source_index,
                    "sentence_index": sentence_index,
                    "sentences": sentences,
                    "item": item,
                }
            )

    if not candidates:
        return sources[:1]

    candidates.sort(
        key=lambda item: item["score"],
        reverse=True,
    )

    best = candidates[0]
    sentences = best["sentences"]
    center = best["sentence_index"]

    # Keep only a tiny local window around the strongest sentence.
    start = max(
        0,
        center - 1,
    )
    end = min(
        len(sentences),
        center + 2,
    )

    excerpt = " ".join(
        str(sentence).strip()
        for sentence in sentences[start:end]
        if str(sentence).strip()
    ).strip()

    selected = dict(
        best["item"]
    )

    selected_row = dict(
        selected["row"]
    )
    selected_row["text"] = excerpt
    selected["row"] = selected_row

    print(
        "[RAG] Definition focus: "
        f"source={best['source_index'] + 1} "
        f"sentence={best['sentence_index'] + 1} "
        f"score={best['score']:.3f}"
    )

    return [selected]


# =========================================================
# DEFINITION PROMPT
# =========================================================

def _build_definition_prompt(
    question,
    sources,
):
    evidence_parts = []

    for item in sources:
        row = item["row"]

        evidence_parts.append(
            str(
                row.get(
                    "text",
                    "",
                )
            ).strip()
        )

    evidence = "\n\n".join(
        part
        for part in evidence_parts
        if part
    )

    return f"""
You are an AI Teaching Assistant.

Answer the user's question using ONLY the focused lecture excerpt below.

USER QUESTION:

{question}

FOCUSED LECTURE EXCERPT:

{evidence}

STRICT RULES:

1. Use only information contained in the focused lecture excerpt.
2. Do not use outside knowledge.
3. Do not invent facts or examples.
4. Answer the question directly in 1 to 3 clear sentences.
5. The first sentence must directly explain what the requested concept is, if the excerpt supports that.
6. Use the lecture's terminology and meaning.
7. Ignore sentences that do not directly help answer the user's question.
8. Do not mention the lecture, transcript, excerpt, evidence, retrieval, embeddings, or the AI system.
9. Do not include timestamps.
10. Do not explain your reasoning.
11. Do not start with meta-commentary such as "Based on the transcript" or "The lecture says".
12. Do not add information that is not supported by the excerpt.
13. Return ONLY the final answer.

If the excerpt does not contain enough information to answer the question, return exactly:

I couldn't find this information in the uploaded course material.

Answer:
""".strip()


def _definition_answer_is_valid(
    question,
    answer,
):
    """Reject obvious off-topic or meta answers from the generator."""

    answer = str(
        answer or ""
    ).strip()

    if not answer:
        return False

    if answer == NOT_FOUND_MESSAGE:
        return False

    topic = _extract_question_topic(
        question
    )

    if topic and (
        _phrase_score(
            topic,
            answer,
        ) < 1.0
        and _keyword_score(
            topic,
            answer,
        ) < 0.40
    ):
        return False

    lower = answer.lower()

    forbidden_meta = [
        "based on the transcript",
        "according to the transcript",
        "the transcript",
        "lecture transcript",
        "transcript 1",
        "transcript 2",
        "transcript 3",
        "the evidence",
        "retrieval",
        "embedding",
    ]

    if any(
        phrase in lower
        for phrase in forbidden_meta
    ):
        return False

    return True


# =========================================================
# PROMPT FOR COMPLEX QUESTIONS
# =========================================================

def _build_prompt(
    question,
    sources,
):
    evidence_parts = []

    for index, item in enumerate(
        sources,
        start=1,
    ):
        row = item["row"]

        evidence_parts.append(
            f"EVIDENCE {index}\n"
            f"Video: {row['title']}\n"
            f"Start: {_format_timestamp(row['start'])}\n"
            f"End: {_format_timestamp(row['end'])}\n"
            f"Transcript: {row['text']}"
        )

    evidence = "\n\n".join(
        evidence_parts
    )

    return f"""
You are an AI Teaching Assistant.

Answer the user's question using ONLY the transcript evidence below.

USER QUESTION:

{question}

TRANSCRIPT EVIDENCE:

{evidence}

STRICT RULES:

1. Use only information contained in the transcript evidence.
2. Do not use outside knowledge.
3. Do not invent facts.
4. Do not invent timestamps.
5. Do not mention the retrieval process.
6. Do not mention embeddings.
7. Do not mention the evidence.
8. Do not explain your reasoning.
9. Do not write analysis.
10. Do not start with "Okay", "Hmm", "The user", "We need to", or similar reasoning text.
11. Give a short, direct answer.
12. If the transcript does not contain enough information, say exactly:

I couldn't find this information in the uploaded course material.

IMPORTANT:

Return ONLY the final answer.

Do not return your reasoning.

Do not return a "Referenced in" section.

Do not return headings.

Answer:
""".strip()


# =========================================================
# RESULT
# =========================================================

def _result(
    answer,
    sources,
):
    references = []

    for item in sources:
        references.append(
            _source_dict(item)
        )

    result = {
        "answer": answer,
        "sources": references,
        "references": references,
    }

    # -----------------------------------------------------
    # Include strongest video information for frontend.
    # -----------------------------------------------------

    if references:
        strongest = references[0]

        result["video"] = {
            "video_id": strongest["video_id"],
            "number": strongest["number"],
            "title": strongest["title"],
            "start": strongest["start"],
            "end": strongest["end"],
            "start_timestamp": strongest[
                "start_timestamp"
            ],
            "end_timestamp": strongest[
                "end_timestamp"
            ],
        }

        result["video_id"] = strongest[
            "video_id"
        ]

    else:
        result["video"] = None
        result["video_id"] = None

    return result


# =========================================================
# MAIN ANSWER FUNCTION
# =========================================================

def answer_question(
    question,
    video_id=None,
):
    started = time.perf_counter()

    question = str(
        question or ""
    ).strip()

    if not question:
        return _result(
            NOT_FOUND_MESSAGE,
            [],
        )

    normalized_question = _normalize_question(
        question
    )

    print(
        f"[RAG] Question: {question}"
    )

    print(
        f"[RAG] Normalized: "
        f"{normalized_question}"
    )

    qtype = _detect_question_type(
        normalized_question
    )

    print(
        f"[RAG] Question type: {qtype}"
    )

    # -----------------------------------------------------
    # 1. Retrieve candidate evidence
    # -----------------------------------------------------

    sources = _retrieve(
        normalized_question,
        video_id=video_id,
    )

    if not sources:
        print(
            "[RAG] No relevant sources found."
        )

        return _result(
            NOT_FOUND_MESSAGE,
            [],
        )

    # -----------------------------------------------------
    # 2. Merge adjacent chunks
    # -----------------------------------------------------

    merged = _merge_adjacent_sources(
        sources
    )

    # -----------------------------------------------------
    # 3. Evidence Validation
    # -----------------------------------------------------

    validated = _validate_evidence(
        normalized_question,
        merged,
    )

    if not validated:
        elapsed = (
            time.perf_counter()
            - started
        )

        print(
            "[RAG] No sufficiently strong evidence "
            f"after validation. "
            f"Completed in {elapsed:.2f}s"
        )

        return _result(
            NOT_FOUND_MESSAGE,
            [],
        )

    # -----------------------------------------------------
    # 4. Select final evidence
    # -----------------------------------------------------

    top_k = max(
        int(
            getattr(
                Config,
                "TOP_K",
                3,
            )
        ),
        1,
    )

    merged = validated[:top_k]

    print(
        f"[RAG] Final validated evidence: "
        f"{len(merged)} chunks"
    )

    # -----------------------------------------------------
    # 5. Location questions
    #
    # No Qwen required.
    # -----------------------------------------------------

    if qtype == "location":
        answer = _build_location_answer(
            normalized_question,
            merged,
        )

        if answer:
            elapsed = (
                time.perf_counter()
                - started
            )

            print(
                f"[RAG] Location answer completed "
                f"in {elapsed:.2f}s"
            )

            return _result(
                _clean_answer(answer),
                merged,
            )

        print(
            "[RAG] Location evidence could not "
            "be confirmed."
        )

        return _result(
            NOT_FOUND_MESSAGE,
            [],
        )

    # -----------------------------------------------------
    # 6. Definition questions
    #
    # Definition answers are extracted directly from the
    # validated lecture transcript. Qwen is intentionally not
    # used here because the transcript already contains the
    # definition and direct extraction prevents prompt leakage,
    # hallucination, and unnecessary generation time.
    # -----------------------------------------------------

    if qtype == "definition":
        extracted = _definition_answer(
            normalized_question,
            merged,
        )

        if extracted:
            answer, best_source = extracted

            elapsed = (
                time.perf_counter()
                - started
            )

            print(
                "[RAG] Extractive definition answer "
                f"completed in {elapsed:.2f}s"
            )

            return _result(
                _clean_answer(answer),
                [best_source],
            )

        print(
            "[RAG] Definition evidence was not "
            "strong enough for extraction."
        )

        return _result(
            NOT_FOUND_MESSAGE,
            [],
        )

    # -----------------------------------------------------
    # 7. List questions
    #
    # These require actual list/classification evidence.
    # Once validated, Qwen can synthesize the answer from
    # the validated transcript chunks.
    # -----------------------------------------------------

    if qtype == "list":
        try:
            prompt = _build_prompt(
                normalized_question,
                merged,
            )

            generation_started = (
                time.perf_counter()
            )

            raw_answer = (
                ollama_service.generate(
                    prompt
                )
            )

            generation_elapsed = (
                time.perf_counter()
                - generation_started
            )

            print(
                f"[RAG] List answer generation "
                f"completed in {generation_elapsed:.2f}s"
            )

        except ollama_service.OllamaError:
            raise

        except Exception as exc:
            raise ollama_service.OllamaError(
                f"Answer generation failed: {exc}"
            ) from exc

        answer = _clean_answer(
            raw_answer
        )

        if not answer:
            answer = NOT_FOUND_MESSAGE

        lower_answer = (
            answer.lower().strip()
        )

        if lower_answer in {
            "i don't know",
            "i don't know.",
            "not enough information",
            "not enough information.",
            "unknown",
            "unknown.",
        }:
            answer = NOT_FOUND_MESSAGE

        elapsed = (
            time.perf_counter()
            - started
        )

        print(
            f"[RAG] List answer completed "
            f"in {elapsed:.2f}s"
        )

        return _result(
            answer,
            merged,
        )

    # -----------------------------------------------------
    # 8. Complex questions
    #
    # Use Qwen only when synthesis is required.
    # -----------------------------------------------------

    try:
        prompt = _build_prompt(
            normalized_question,
            merged,
        )

        generation_started = (
            time.perf_counter()
        )

        raw_answer = (
            ollama_service.generate(
                prompt
            )
        )

        generation_elapsed = (
            time.perf_counter()
            - generation_started
        )

        print(
            f"[RAG] Generation completed "
            f"in {generation_elapsed:.2f}s"
        )

    except ollama_service.OllamaError:
        raise

    except Exception as exc:
        raise ollama_service.OllamaError(
            f"Answer generation failed: {exc}"
        ) from exc

    # -----------------------------------------------------
    # Clean model response
    # -----------------------------------------------------

    answer = _clean_answer(
        raw_answer
    )

    # -----------------------------------------------------
    # Safety fallback
    # -----------------------------------------------------

    if not answer:
        answer = NOT_FOUND_MESSAGE

    lower_answer = answer.lower().strip()

    if lower_answer in {
        "i don't know",
        "i don't know.",
        "not enough information",
        "not enough information.",
        "unknown",
        "unknown.",
    }:
        answer = NOT_FOUND_MESSAGE

    elapsed = (
        time.perf_counter()
        - started
    )

    print(
        f"[RAG] Answer completed "
        f"in {elapsed:.2f}s"
    )

    return _result(
        answer,
        merged,
    )


# =========================================================
# OPTIONAL ALIAS
# =========================================================

def ask_question(
    question,
    video_id=None,
):
    return answer_question(
        question,
        video_id=video_id,
    )